modLoader="javafml"
loaderVersion="[31,)"
license="GNU General Public License"
issueTrackerURL="https://github.com/RayTrace082/untamedwilds/issues"
[[mods]]
modId="untamedwilds"
version="1.0.0"
displayName="Untamed Wilds"
# updateJSONURL="http://myurl.me/" #optional
displayURL="https://github.com/RayTrace082/untamedwilds/"
logoFile="logo.png"
# credits="" #optional
authors="RayTrace082"

description='''Expanding on the natural world of Minecraft.'''

[[dependencies.citadel]]
    modId="citadel"
    mandatory=true
    versionRange="[1.6.0,)"
    ordering="AFTER"
    side="BOTH"
