modLoader="javafml"
loaderVersion="[31,)"
license="GNU General Public License"
issueTrackerURL="https://github.com/RayTrace082/untamedwilds/issues"
[[mods]]
modId="untamedwilds"
version="${file.jarVersion}"
displayName="Untamed Wilds"
# updateJSONURL="http://myurl.me/" #optional
# displayURL="http://example.com/" #optional
# logoFile="examplemod.png" #optional
# credits="" #optional
authors="RayTrace082"

description='''Expanding on the natural world of Minecraft.'''

[[dependencies.citadel]]
    modId="citadel"
    mandatory=true
    versionRange="[1.6.0,)"
    ordering="AFTER"
    side="BOTH"
